### ISSUE TITLE
error while checkout to master

### ISSUE THREAD

**Issue by maku0** [sunplus-plus1/SP7021#1]
command:
git submodule foreach --recursive git checkout master
Error:
Your branch is up to date with 'origin/master'.
Entering 'linux/kernel'
error: invalid path 'drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.c'
error: invalid path 'drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.h'
error: invalid path 'include/soc/arc/aux.h'
fatal: run_command returned non-zero status for linux/kernel

**Comment by sunplus-plus1** [comment]
Hi maku0,
The reason of invalid path error is mentioned in the Issues of sunplus-plus1/linux. so please run on Ubuntu or 
run 'git submodule foreach --recursive git config core.protectNTFS false' then 'git submodule foreach git checkout master'. of course, prefix "aux" file were not existe. please add them as other name by manual.
