### ISSUE TITLE
Device Tree Source is not correctly specified.

### ISSUE THREAD

**Issue by versamodule** [sunplus-plus1/SP7021#2]
Everything work ok until i did "make all" 
it went for a bit then I got this. 

../../linux/kernel/dtb
Device Tree Source is not correctly specified.
Please define 'CONFIG_DEFAULT_DEVICE_TREE'
or build with 'DEVICE_TREE=<device_tree>' argument

**Comment by sunplus-plus1** [comment]
What board is your selected?

**Comment by versamodule** [comment]
BPI-FS2

Sincerely,

Jimp@Versamodule.com

**Comment by versamodule** [comment]
BPI-FS2

**Comment by sunplus-plus1** [comment]
I git clone and follow compile step to do again, everything works find. Your problem is that dtb didn't be created, Did you follow "How to compile" step to compile? If yes, please run 'make dtb' and post those message for me, thanks.

**Comment by versamodule** [comment]
I followed each step.  I ran 'make dtb' here is the output. 

> jim@ubuntu:~/SP7021_4.19$ make dtb
> make[1]: Entering directory '/home/jim/SP7021_4.19/linux/kernel'
>   HOSTCC  scripts/extract-cert
> scripts/extract-cert.c:21:10: fatal error: openssl/bio.h: No such file or directory
>  #include <openssl/bio.h>
>           ^~~~~~~~~~~~~~~
> compilation terminated.
> scripts/Makefile.host:90: recipe for target 'scripts/extract-cert' failed
> make[2]: *** [scripts/extract-cert] Error 1
> Makefile:1067: recipe for target 'scripts' failed
> make[1]: *** [scripts] Error 2
> make[1]: Leaving directory '/home/jim/SP7021_4.19/linux/kernel'
> make uboot
> make[1]: Entering directory '/home/jim/SP7021_4.19'
> make[2]: Entering directory '/home/jim/SP7021_4.19/boot/uboot'
>   CHK     include/config/uboot.release
>   CHK     include/generated/timestamp_autogenerated.h
>   UPD     include/generated/timestamp_autogenerated.h
>   CHK     include/generated/version_autogenerated.h
>   CHK     include/generated/generic-asm-offsets.h
>   CHK     include/generated/asm-offsets.h
>   HOSTCC  tools/mkenvimage.o
>   HOSTCC  tools/fit_image.o
>   HOSTCC  tools/image-host.o
>   HOSTCC  tools/dumpimage.o
>   HOSTCC  tools/mkimage.o
>   HOSTLD  tools/mkenvimage
>   HOSTLD  tools/dumpimage
>   HOSTLD  tools/mkimage
>   CC      common/main.o
>   CC      cmd/version.o
>   CC      lib/smbios.o
>   CC      lib/display_options.o
>   LD      cmd/built-in.o
>   LD      common/built-in.o
>   CC      lib/efi_loader/helloworld.o
>   CC      lib/efi_loader/efi_reloc.o
>   CC      lib/efi_loader/efi_freestanding.o
>   LD      lib/efi_loader/helloworld_efi.so
>   OBJCOPY lib/efi_loader/helloworld.efi
>   LD      lib/built-in.o
>   LD      u-boot
>   SYM     u-boot.sym
>   OBJCOPY u-boot.srec
>   OBJCOPY u-boot-nodtb.bin
> 
> ../../linux/kernel/dtb
> Device Tree Source is not correctly specified.
> Please define 'CONFIG_DEFAULT_DEVICE_TREE'
> or build with 'DEVICE_TREE=<device_tree>' argument
> 
> dts/Makefile:28: recipe for target '../../linux/kernel/dtb' failed
> make[3]: *** [../../linux/kernel/dtb] Error 1
> Makefile:1041: recipe for target 'dts/dt.dtb' failed
> make[2]: *** [dts/dt.dtb] Error 2
> make[2]: *** Waiting for unfinished jobs....
> make[2]: Leaving directory '/home/jim/SP7021_4.19/boot/uboot'
> build/Makefile:92: recipe for target 'uboot' failed
> make[1]: *** [uboot] Error 2
> make[1]: Leaving directory '/home/jim/SP7021_4.19'
> build/Makefile:154: recipe for target 'dtb' failed
> make: *** [dtb] Error 2
> jim@ubuntu:~/SP7021_4.19$

**Comment by sunplus-plus1** [comment]
please install:
sudo apt-get install openssl
sudo apt-get install libssl-dev
and try again, thanks.

**Comment by versamodule** [comment]
ok, it went much further this time, but still failed. 

Just showing the last little bit. 

>   DEPMOD  4.19.37-g5c0cf40a7
> make[2]: Leaving directory '/home/jim/SP7021_4.19/linux/kernel'
> make[2]: Entering directory '/home/jim/SP7021_4.19/linux/kernel'
>   CALL    scripts/checksyscalls.sh
>   CHK     include/generated/compile.h
>   Kernel: arch/arm/boot/Image is ready
>   Kernel: arch/arm/boot/zImage is ready
>   UIMAGE  arch/arm/boot/uImage
> "mkimage" command not found - U-Boot images will not be built
> arch/arm/boot/Makefile:90: recipe for target 'arch/arm/boot/uImage' failed
> make[3]: *** [arch/arm/boot/uImage] Error 1
> arch/arm/Makefile:338: recipe for target 'uImage' failed
> make[2]: *** [uImage] Error 2
> make[2]: Leaving directory '/home/jim/SP7021_4.19/linux/kernel'
> build/Makefile:102: recipe for target 'kernel' failed
> make[1]: *** [kernel] Error 2
> make[1]: Leaving directory '/home/jim/SP7021_4.19'
> build/Makefile:292: recipe for target 'all' failed
> make: *** [all] Error 2
> jim@ubuntu:~/SP7021_4.19$

**Comment by versamodule** [comment]
ok, i needed to also do: sudo apt-get install u-boot-tools

Now it all worked. I guess there just needed to be some prerequisites installed first.
The only confusing thing left is if i selected eMMC option, how do we take the files from the out folder and get them onto the eMMC.

**Comment by sunplus-plus1** [comment]
great, you just copy ISPBOOOT.BIN in out folder to your USB disc and 
1) power off, put it into board's USB socket, switch DIP 1 to on, power on, board will update from USB disc to eMMC
2) power off, switch DIP 1 to off, power on, board will boot from eMMC to kernel.

**Comment by versamodule** [comment]
I'll give that a try tomorrow.  Thank you so much for your help!

**Comment by sunplus-plus1** [comment]
You are welcome, thanks your feedback too.

**Comment by versamodule** [comment]
I copied ISPBOOT.bin to a USB stick. Set SW1 to ON and SW2 to off. 
Power it on and it just keeps repeating the same message below. 

+++iBoot v1.02 Jan 10 2019 11:20:28
-- B --
[d] iboot.c :96
[d] iboot.c :107
[d] iboot.c :877
hw_cfg=0x00017FFF
bootmode=0x00000017
[d] iboot.c :813
[d] iboot.c :316

[[usb_isp]]
usb0
[d] bootmain.c :116
dev=1 pin=0
find file
[d] fat_boot.c :181
[d] fat_boot.c :189
[d] ehci_usb.c :229
[d] ehci_usb.c :239

Reset EHCI
.........................
No usb device on port 0
[d] fat_boot.c :213
[d] iboot.c :285
not found
usb1
[d] bootmain.c :116
dev=1 pin=0
find file
[d] fat_boot.c :181
[d] fat_boot.c :189
[d] ehci_usb.c :229
[d] ehci_usb.c :239

Reset EHCI

usb1 connected(0ms)
enum u-disk
get dev desc (64)
[d] ehci_usb.c :727
Setup 8
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 64
[d] ehci_usb.c :653
[d] ehci_usb.c :701
Out 0
[d] ehci_usb.c :653
[d] ehci_usb.c :701
[d] ehci_usb.c :762
vid=13 FE pid=55 00 rev=01 00
set addr
[d] ehci_usb.c :727
Setup 8
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 0
[d] ehci_usb.c :653
[d] ehci_usb.c :701
[d] ehci_usb.c :762
get dev desc (18)
[d] ehci_usb.c :727
Setup 8
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 18
[d] ehci_usb.c :653
[d] ehci_usb.c :701
Out 0
[d] ehci_usb.c :653
[d] ehci_usb.c :701
[d] ehci_usb.c :762
get conf desc (9)
[d] ehci_usb.c :727
Setup 8
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 9
[d] ehci_usb.c :653
[d] ehci_usb.c :701
Out 0
[d] ehci_usb.c :653
[d] ehci_usb.c :701
[d] ehci_usb.c :762
get conf desc (9)
[d] ehci_usb.c :727
Setup 8
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 32
[d] ehci_usb.c :653
[d] ehci_usb.c :701
Out 0
[d] ehci_usb.c :653
[d] ehci_usb.c :701
[d] ehci_usb.c :762
set config 1
[d] ehci_usb.c :727
Setup 8
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 0
[d] ehci_usb.c :653
[d] ehci_usb.c :701
[d] ehci_usb.c :762
Test Unit Ready (0)
[d] ehci_usb.c :459
[d] ehci_usb.c :775
Out 31
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 13
[d] ehci_usb.c :653
[d] ehci_usb.c :701
[d] ehci_usb.c :842
Test Unit Ready (1)
[d] ehci_usb.c :459
[d] ehci_usb.c :775
Out 31
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 13
[d] ehci_usb.c :653
[d] ehci_usb.c :701
[d] ehci_usb.c :842
Test Unit Ready (2)
[d] ehci_usb.c :459
[d] ehci_usb.c :775
Out 31
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 13
[d] ehci_usb.c :653
[d] ehci_usb.c :701
[d] ehci_usb.c :842
Test Unit Ready (3)
[d] ehci_usb.c :459
[d] ehci_usb.c :775
Out 31
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 13
[d] ehci_usb.c :653
[d] ehci_usb.c :701
[d] ehci_usb.c :842
Test Unit Ready (4)
[d] ehci_usb.c :459
[d] ehci_usb.c :775
Out 31
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 13
[d] ehci_usb.c :653
[d] ehci_usb.c :701
[d] ehci_usb.c :842
[d] fat_boot.c :218
[d] ehci_usb.c :534
[d] ehci_usb.c :775
Out 31
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 512
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 13
[d] ehci_usb.c :653
[d] ehci_usb.c :701
[d] ehci_usb.c :842
[d] fat_boot.c :230
part@0x00008000
[d] ehci_usb.c :534
[d] ehci_usb.c :775
Out 31
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 512
[d] ehci_usb.c :653
[d] ehci_usb.c :701
In 13
[d] ehci_usb.c :653
[d] ehci_usb.c :701
[d] ehci_usb.c :842
[d] fat_boot.c :259
Not fat32
[d] iboot.c :285
not found
[d] iboot.c :877
hw_cfg=0x00017FFF
bootmode=0x00000017
[d] iboot.c :813
[d] iboot.c :316

[[usb_isp]]
usb0
[d] bootmain.c :116
dev=1 pin=0
find file
[d] fat_boot.c :181
[d] fat_boot.c :189
[d] ehci_usb.c :229
[d] ehci_usb.c :239

Reset EHCI
.........


Here is a screen shot of the final 'make all', and also the out folder. The files seem way to small to put Linux OS on eMMC. 

![Annotation 2020-06-04 235216](https://user-images.githubusercontent.com/6456652/83838489-f0131180-a6be-11ea-8bfa-77968095be59.jpg)

**Comment by sunplus-plus1** [comment]
Check your message, found "Not fat32". So please format your USB stick to "FAT32" and try again. The ISPBOOOT.BIN is 22.6 MBytes because rootfs.img is just only include busybox function.
